### ISSUE TITLE
Exceptions using Base:Circle while changing Order and Index

### ISSUE THREAD

**Issue by andreygursky** [magin67/Spectroscope#6]
Hi Dmitry,

thanks for the article! I've just given a try using git 2ea383ede27e2453b607f12fb51ddd5492234740 and by moving randomly slide-bars encountered a couple of exceptions:

```python
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.5/tkinter/__init__.py", line 1562, in __call__
    return self.func(*args)
  File "/usr/lib/python3.5/tkinter/__init__.py", line 3300, in __call__
    self.__callback(self.__value, *args)
  File "Spectroscope.py", line 54, in ChangeBaseSet
    self.shSpectr.SetForm()
  File "SpectrData.py", line 335, in SetForm
    self.SetColor(-1)
  File "SpectrData.py", line 315, in SetColor
    self.vColor = self.vDataZ[self.iColor]
IndexError: list index out of range
```

and

```python
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.5/tkinter/__init__.py", line 1562, in __call__
    return self.func(*args)
  File "Spectroscope.py", line 65, in ChangeIndex
    self.shSpectr.ChangeIndex(ind*self.shSpectr.NumPlots)
  File "SpectrData.py", line 290, in ChangeIndex
    self.ShowSp()
  File "SpectrData.py", line 286, in ShowSp
    self.UpdateSpectr(ax, self.vDataX[cIndex], self.vDataY[cIndex], vSize, vColor, title)
  File "SpectrData.py", line 248, in UpdateSpectr
    ax.tripcolor(triang, self.vColor, edgecolors='none', cmap=cmap, alpha=self.alpha) #shading='flat'
  File "/usr/lib/python3/dist-packages/matplotlib/axes/_axes.py", line 7677, in tripcolor
    return mtri.tripcolor(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/tri/tripcolor.py", line 92, in tripcolor
    raise ValueError('Length of color values array must be the same '
ValueError: Length of color values array must be the same as either the number of triangulation points or triangles
```

Regards,
Andrey

**Comment by magin67** [comment]
Hm, I can't get these exceptions. Can you give more info about what are you doing? Thanks.

**Comment by andreygursky** [comment]
For the first one: start, then switch base from Hex to Circle. For the second one is harder to reproduce.

**Comment by andreygursky** [comment]
Exception N3 (without reproducer yet.):
```python
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.5/tkinter/__init__.py", line 1562, in __call__
    return self.func(*args)
  File "/usr/lib/python3.5/tkinter/__init__.py", line 3300, in __call__
    self.__callback(self.__value, *args)
  File "Spectroscope.py", line 121, in SetPlotType
    self.shSpectr.ShowSp()
  File "SpectrData.py", line 286, in ShowSp
    self.UpdateSpectr(ax, self.vDataX[cIndex], self.vDataY[cIndex], vSize, vColor, title)
  File "SpectrData.py", line 254, in UpdateSpectr
    ax.tricontour(triang, self.vColor, colors='blue', alpha=self.alpha) #'k'
  File "/usr/lib/python3/dist-packages/matplotlib/axes/_axes.py", line 7669, in tricontour
    return mtri.tricontour(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/tri/tricontour.py", line 278, in tricontour
    return TriContourSet(ax, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/tri/tricontour.py", line 40, in __init__
    ContourSet.__init__(self, ax, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/contour.py", line 864, in __init__
    self._process_args(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/tri/tricontour.py", line 51, in _process_args
    tri, z = self._contour_args(args, kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/tri/tricontour.py", line 87, in _contour_args
    raise ValueError('z array must have same length as triangulation x'
ValueError: z array must have same length as triangulation x and y arrays
```

**Comment by magin67** [comment]
Exception N1 is fixed
